# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go get github.com/gogo/protobuf/protoc-gen-gofast
    - go install github.com/gogo/protobuf/protoc-gen-gofast
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    id: "Server"
    main: ./server/.
    binary: goMarkableStreamServer.arm
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
  - env:
      - CGO_ENABLED=0
    id: "Client"
    main: ./client/.
    binary: goMarkableClient
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format_overrides:
    - goos: windows
      format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
